#ifndef PORTS_HPP_
#define PORTS_HPP_

enum PortIndex {
	BSILENT_MIDI_IN  = 0,
	BSILENT_AUDIO_OUT = 1,
	BSILENT_CONTROLLERS = 2,
	BSILENT_PRESET = 0,
	BSILENT_GAIN = 1,
	BSILENT_TUNE = 2,
	BSILENT_NR_CONTROLLERS = 3,
	BSILENT_N_PORTS = BSILENT_CONTROLLERS + BSILENT_NR_CONTROLLERS
};

#endif /* PORTS_HPP_ */
